### ISSUE TITLE
Práctica Architect 

### ISSUE THREAD

**Issue by Jaczibeth** [SistemasTecTlaxiaco/actividad-3-practica-architect-Jaczibeth-1#1]
[Reporte - Architect.pdf](https://github.com/user-attachments/files/16856831/Reporte.-.Architect.pdf)

Práctica elaborada por:
Jaczibeth Cruz Ramirez
Daniel Velasco López 
Kevin Andrew Osorio Aparicio

**Comment by MarleneRamirez0731** [comment]
Cumple con todo dentro de la rúbrica

**Comment by josealfredo79** [comment]
bien hecho y revisado..
